In [1]:
import polars as pl

In [2]:
event_lf = pl.scan_parquet('data/event_full_2025.parquet')
items_lf = pl.scan_parquet('data/items.parquet')
transaction_lf = pl.scan_parquet('data/transaction_full_2025.parquet')

In [3]:
display(transaction_lf.head(5).collect())
display(event_lf.head(5).collect())

display(items_lf.head(5).collect())

shape: (5, 9)
┌────────────┬───────────┬───────────┬──────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ customer_i ┆ item_id   ┆ price     ┆ location ┆ … ┆ bill_id   ┆ quantity ┆ event_typ ┆ updated_d │
│ d          ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---      ┆ e         ┆ ate       │
│ ---        ┆ str       ┆ decimal[3 ┆ i32      ┆   ┆ i32       ┆ i32      ┆ ---       ┆ ---       │
│ i32        ┆           ┆ 8,4]      ┆          ┆   ┆           ┆          ┆ str       ┆ datetime[ │
│            ┆           ┆           ┆          ┆   ┆           ┆          ┆           ┆ μs]       │
╞════════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 6291331    ┆ 676700000 ┆ 285000.00 ┆ 1053     ┆ … ┆ 137262467 ┆ 1        ┆ Purchase  ┆ 2025-04-1 │
│            ┆ 0002      ┆ 00        ┆          ┆   ┆           ┆          ┆           ┆ 2 12:52:4 │
│            ┆           ┆           ┆          ┆   ┆           ┆          ┆           ┆ 1.910     │
│ 5505362    ┆ 226500000 ┆ 195000.00 ┆ 468      ┆ … ┆ 138193104 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 0027      ┆ 00        ┆          ┆   ┆           ┆          ┆           ┆ 4 14:57:0 │
│            ┆           ┆           ┆          ┆   ┆           ┆          ┆           ┆ 0.773     │
│ 7694873    ┆ 649700000 ┆ 312550.00 ┆ 363      ┆ … ┆ 138230425 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 0004      ┆ 00        ┆          ┆   ┆           ┆          ┆           ┆ 4 20:35:4 │
│            ┆           ┆           ┆          ┆   ┆           ┆          ┆           ┆ 0.027     │
│ 5837076    ┆ 658700000 ┆ 149000.00 ┆ 48       ┆ … ┆ 138235471 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 0001      ┆ 00        ┆          ┆   ┆           ┆          ┆           ┆ 4 21:12:3 │
│            ┆           ┆           ┆          ┆   ┆           ┆          ┆           ┆ 2.070     │
│ 6781756    ┆ 388000000 ┆ 79000.000 ┆ 634      ┆ … ┆ 138239415 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 0002      ┆ 0         ┆          ┆   ┆           ┆          ┆           ┆ 5 08:00:4 │
│            ┆           ┆           ┆          ┆   ┆           ┆          ┆           ┆ 6.293     │
└────────────┴───────────┴───────────┴──────────┴───┴───────────┴──────────┴───────────┴───────────┘

shape: (5, 8)
┌────────────┬────────────┬────────────┬──────────┬────────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ item_id    ┆ price      ┆ quantity ┆ event_type ┆ event_dat ┆ created_d ┆ updated_d │
│ d          ┆ ---        ┆ ---        ┆ ---      ┆ ---        ┆ e         ┆ ate       ┆ ate       │
│ ---        ┆ str        ┆ decimal[38 ┆ i32      ┆ str        ┆ ---       ┆ ---       ┆ ---       │
│ i32        ┆            ┆ ,4]        ┆          ┆            ┆ datetime[ ┆ datetime[ ┆ datetime[ │
│            ┆            ┆            ┆          ┆            ┆ μs]       ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪════════════╪══════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 5390942    ┆ 2265000000 ┆ 325000.000 ┆ 1        ┆ view_item  ┆ 2024-09-0 ┆ 2025-06-0 ┆ 2025-06-0 │
│            ┆ 025        ┆ 0          ┆          ┆            ┆ 6         ┆ 4 22:37:0 ┆ 4 22:37:0 │
│            ┆            ┆            ┆          ┆            ┆ 00:00:00  ┆ 5.605091  ┆ 5.605091  │
│ 2525048    ┆ 2470000000 ┆ 555000.000 ┆ 2        ┆ add_to_car ┆ 2024-09-0 ┆ 2025-06-0 ┆ 2025-06-0 │
│            ┆ 006        ┆ 0          ┆          ┆ t          ┆ 6         ┆ 4 22:37:0 ┆ 4 22:37:0 │
│            ┆            ┆            ┆          ┆            ┆ 00:00:00  ┆ 5.605091  ┆ 5.605091  │
│ 4243782    ┆ 0930030380 ┆ 19000.0000 ┆ 8        ┆ view_item  ┆ 2024-09-0 ┆ 2025-06-0 ┆ 2025-06-0 │
│            ┆ 001        ┆            ┆          ┆            ┆ 6         ┆ 4 22:37:0 ┆ 4 22:37:0 │
│            ┆            ┆            ┆          ┆            ┆ 00:00:00  ┆ 5.605091  ┆ 5.605091  │
│ 6822823    ┆ 6792000000 ┆ 206400.000 ┆ 1        ┆ add_to_car ┆ 2024-09-0 ┆ 2025-06-0 ┆ 2025-06-0 │
│            ┆ 002        ┆ 0          ┆          ┆ t          ┆ 6         ┆ 4 22:37:0 ┆ 4 22:37:0 │
│            ┆            ┆            ┆          ┆            ┆ 00:00:00  ┆ 5.605091  ┆ 5.605091  │
│ 1878879    ┆ 4512000000 ┆ 295000.000 ┆ 1        ┆ view_item  ┆ 2024-09-0 ┆ 2025-06-0 ┆ 2025-06-0 │
│            ┆ 002        ┆ 0          ┆          ┆            ┆ 6         ┆ 4 22:37:0 ┆ 4 22:37:0 │
│            ┆            ┆            ┆          ┆            ┆ 00:00:00  ┆ 5.605091  ┆ 5.605091  │
└────────────┴────────────┴────────────┴──────────┴────────────┴───────────┴───────────┴───────────┘

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ manufactu ┆ descripti ┆ sale_stat ┆ size     │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rer       ┆ on        ┆ us        ┆ ---      │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ i32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000804000 ┆ 115000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Robo Luồn ┆ 0         ┆ Không    │
│ 0046      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ thun Winw ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ intoys có ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ h…        ┆           ┆          │
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Không    │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ định      ┆ định      ┆           ┆ xác định │
│ 000701000 ┆ 102000.00 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ Với hơn   ┆ 0         ┆ Không    │
│ 0886      ┆ 00        ┆           ┆ phụ kiện  ┆   ┆ định      ┆ 60 năm    ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ qua, trải ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ qua r…    ┆           ┆          │
│ 050202034 ┆ 228000.00 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ Bình ủ    ┆ 0         ┆ Không    │
│ 0030      ┆ 00        ┆           ┆ phụ kiện  ┆   ┆ định      ┆ sữa của   ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ KuKu của  ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Đài Lo…   ┆           ┆          │
│ 001205000 ┆ 59000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Không    │
│ 0007      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆           ┆ xác định │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [65]:
report_transaction_lf = transaction_lf.select(
    pl.col('price').min().alias('min_price'),
    pl.col('price').max().alias('max_price'),
    pl.col('discount').min().alias('min_discount'),
    pl.col('discount').max().alias('max_discount'),
    pl.col('quantity').min().alias('min_quantity'),
    pl.col('quantity').max().alias('max_quantity'),
    pl.col('updated_date').min().alias('min_updated_date'),
    pl.col('updated_date').max().alias('max_updated_date')
)

display(report_transaction_lf.collect(engine = "streaming"))

shape: (1, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ min_price  ┆ max_price  ┆ min_discou ┆ max_disco ┆ min_quant ┆ max_quant ┆ min_updat ┆ max_updat │
│ ---        ┆ ---        ┆ nt         ┆ unt       ┆ ity       ┆ ity       ┆ ed_date   ┆ ed_date   │
│ decimal[38 ┆ decimal[38 ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ ,4]        ┆ ,4]        ┆ decimal[38 ┆ decimal[3 ┆ i32       ┆ i32       ┆ datetime[ ┆ datetime[ │
│            ┆            ┆ ,4]        ┆ 8,4]      ┆           ┆           ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0001     ┆ 20990000.0 ┆ 0.0000     ┆ 13200000. ┆ 1         ┆ 1400      ┆ 2025-01-0 ┆ 2025-12-3 │
│            ┆ 000        ┆            ┆ 0000      ┆           ┆           ┆ 1 06:51:0 ┆ 1 22:30:3 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 5.690     ┆ 0.267     │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [66]:
report_event_lf = event_lf.select(
    pl.col('price').min().alias('min_price'),
    pl.col('price').max().alias('max_price'),
    pl.col('quantity').min().alias('min_quantity'),
    pl.col('quantity').max().alias('max_quantity'),
    pl.col('event_date').min().alias('min_date'),
    pl.col('event_date').max().alias('max_date')
)

display(report_event_lf.collect(engine = "streaming"))

shape: (1, 6)
┌───────────────┬───────────────┬──────────────┬──────────────┬──────────────────┬─────────────────┐
│ min_price     ┆ max_price     ┆ min_quantity ┆ max_quantity ┆ min_date         ┆ max_date        │
│ ---           ┆ ---           ┆ ---          ┆ ---          ┆ ---              ┆ ---             │
│ decimal[38,4] ┆ decimal[38,4] ┆ i32          ┆ i32          ┆ datetime[μs]     ┆ datetime[μs]    │
╞═══════════════╪═══════════════╪══════════════╪══════════════╪══════════════════╪═════════════════╡
│ -9201000.0000 ┆ 20990000.0000 ┆ 1            ┆ 37958        ┆ 2024-05-31       ┆ 2025-12-04      │
│               ┆               ┆              ┆              ┆ 00:00:00         ┆ 00:00:00        │
└───────────────┴───────────────┴──────────────┴──────────────┴──────────────────┴─────────────────┘

In [67]:
### số lượng dòng có created_date == updated_date
display(event_lf.select((pl.col('created_date') != pl.col('updated_date')).sum().alias('total')).collect(engine = "streaming"))

shape: (1, 1)
┌───────┐
│ total │
│ ---   │
│ u32   │
╞═══════╡
│ 0     │
└───────┘

### Lọc dữ liệu 
1. Bảng event
- Lọc các giá trị âm ở cột `price`
- Bỏ đi các cột `created_date` và `updated_date`
- Thêm các cột để đồng nhất với bảng `transaction`

In [85]:
new_event_lf = (event_lf.filter(pl.col('price') >=0)
                .drop(['created_date', 'updated_date'])
                .rename({'event_date': 'updated_date'})
                .with_columns(
                    pl.lit(None).cast(pl.Int32).alias('location'),
                    pl.lit(None).cast(pl.Int32).alias('bill_id'),
                    pl.lit(None).cast(pl.Float32).alias('discount'),
                    pl.col('price').cast(pl.Float32)
                ).select([
                    'customer_id',
                    'item_id',
                    'price',
                    'location',
                    'discount',
                    'bill_id',
                    'quantity',
                    'event_type',
                    'updated_date'
                ])
)

display(new_event_lf.head(5).collect(engine='streaming'))

shape: (5, 9)
┌────────────┬────────────┬──────────┬──────────┬───┬─────────┬──────────┬────────────┬────────────┐
│ customer_i ┆ item_id    ┆ price    ┆ location ┆ … ┆ bill_id ┆ quantity ┆ event_type ┆ updated_da │
│ d          ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---     ┆ ---      ┆ ---        ┆ te         │
│ ---        ┆ str        ┆ f32      ┆ i32      ┆   ┆ i32     ┆ i32      ┆ str        ┆ ---        │
│ i32        ┆            ┆          ┆          ┆   ┆         ┆          ┆            ┆ datetime[μ │
│            ┆            ┆          ┆          ┆   ┆         ┆          ┆            ┆ s]         │
╞════════════╪════════════╪══════════╪══════════╪═══╪═════════╪══════════╪════════════╪════════════╡
│ 5390942    ┆ 2265000000 ┆ 325000.0 ┆ null     ┆ … ┆ null    ┆ 1        ┆ view_item  ┆ 2024-09-06 │
│            ┆ 025        ┆          ┆          ┆   ┆         ┆          ┆            ┆ 00:00:00   │
│ 2525048    ┆ 2470000000 ┆ 555000.0 ┆ null     ┆ … ┆ null    ┆ 2        ┆ add_to_car ┆ 2024-09-06 │
│            ┆ 006        ┆          ┆          ┆   ┆         ┆          ┆ t          ┆ 00:00:00   │
│ 4243782    ┆ 0930030380 ┆ 19000.0  ┆ null     ┆ … ┆ null    ┆ 8        ┆ view_item  ┆ 2024-09-06 │
│            ┆ 001        ┆          ┆          ┆   ┆         ┆          ┆            ┆ 00:00:00   │
│ 6822823    ┆ 6792000000 ┆ 206400.0 ┆ null     ┆ … ┆ null    ┆ 1        ┆ add_to_car ┆ 2024-09-06 │
│            ┆ 002        ┆          ┆          ┆   ┆         ┆          ┆ t          ┆ 00:00:00   │
│ 1878879    ┆ 4512000000 ┆ 295000.0 ┆ null     ┆ … ┆ null    ┆ 1        ┆ view_item  ┆ 2024-09-06 │
│            ┆ 002        ┆          ┆          ┆   ┆         ┆          ┆            ┆ 00:00:00   │
└────────────┴────────────┴──────────┴──────────┴───┴─────────┴──────────┴────────────┴────────────┘

In [86]:
new_transaction_lf = (
    transaction_lf.with_columns(
        pl.col('price').cast(pl.Float32),
        pl.col('discount').cast(pl.Float32),
    )
)

display(new_transaction_lf.head(5).collect(engine = 'streaming'))

shape: (5, 9)
┌────────────┬────────────┬──────────┬──────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ customer_i ┆ item_id    ┆ price    ┆ location ┆ … ┆ bill_id   ┆ quantity ┆ event_typ ┆ updated_d │
│ d          ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---      ┆ e         ┆ ate       │
│ ---        ┆ str        ┆ f32      ┆ i32      ┆   ┆ i32       ┆ i32      ┆ ---       ┆ ---       │
│ i32        ┆            ┆          ┆          ┆   ┆           ┆          ┆ str       ┆ datetime[ │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ μs]       │
╞════════════╪════════════╪══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 6291331    ┆ 6767000000 ┆ 285000.0 ┆ 1053     ┆ … ┆ 137262467 ┆ 1        ┆ Purchase  ┆ 2025-04-1 │
│            ┆ 002        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2 12:52:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 1.910     │
│ 5505362    ┆ 2265000000 ┆ 195000.0 ┆ 468      ┆ … ┆ 138193104 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 027        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 4 14:57:0 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 0.773     │
│ 7694873    ┆ 6497000000 ┆ 312550.0 ┆ 363      ┆ … ┆ 138230425 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 004        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 4 20:35:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 0.027     │
│ 5837076    ┆ 6587000000 ┆ 149000.0 ┆ 48       ┆ … ┆ 138235471 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 001        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 4 21:12:3 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2.070     │
│ 6781756    ┆ 3880000000 ┆ 79000.0  ┆ 634      ┆ … ┆ 138239415 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 002        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 5 08:00:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6.293     │
└────────────┴────────────┴──────────┴──────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
interaction_lf = pl.concat([new_transaction_lf, new_event_lf])

display(interaction_lf.head(5).collect(engine = 'streaming'))

shape: (5, 9)
┌────────────┬────────────┬──────────┬──────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ customer_i ┆ item_id    ┆ price    ┆ location ┆ … ┆ bill_id   ┆ quantity ┆ event_typ ┆ updated_d │
│ d          ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---      ┆ e         ┆ ate       │
│ ---        ┆ str        ┆ f32      ┆ i32      ┆   ┆ i32       ┆ i32      ┆ ---       ┆ ---       │
│ i32        ┆            ┆          ┆          ┆   ┆           ┆          ┆ str       ┆ datetime[ │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ μs]       │
╞════════════╪════════════╪══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 104642     ┆ 3856000000 ┆ 375000.0 ┆ 207      ┆ … ┆ 138240676 ┆ 3        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 001        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 5 08:02:0 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2.483     │
│ 4025147    ┆ 4690000000 ┆ 35000.0  ┆ 144      ┆ … ┆ 138242423 ┆ 3        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 001        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6 16:53:2 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 7.863     │
│ 1776230    ┆ 6768000000 ┆ 345000.0 ┆ 252      ┆ … ┆ 138241281 ┆ 3        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 004        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 5 19:17:2 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 5.047     │
│ 6305030    ┆ 6768000000 ┆ 345000.0 ┆ 212      ┆ … ┆ 137156835 ┆ 3        ┆ Purchase  ┆ 2025-04-1 │
│            ┆ 003        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 0 20:22:5 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2.120     │
│ 4283768    ┆ 0006020000 ┆ 25000.0  ┆ 199      ┆ … ┆ 138242817 ┆ 3        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 282        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 5 08:52:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 1.413     │
└────────────┴────────────┴──────────┴──────────┴───┴───────────┴──────────┴───────────┴───────────┘

### Data splitting
- Data train: trước 1/11/2025
- Data valid: trong tháng 11/2025
- Data test: trong tháng 12/2025

In [96]:
from datetime import datetime

VALID_START = datetime(2025,11,1)
TEST_START = datetime(2025,12,1)
TEST_END = datetime(2025,12,31)

In [104]:
train_set = interaction_lf.filter(pl.col('updated_date') < pl.lit(VALID_START))
valid_set = interaction_lf.filter((pl.col('updated_date') >= pl.lit(VALID_START)) & (pl.col('updated_date') < pl.lit(TEST_START)))
test_set = interaction_lf.filter((pl.col('updated_date') >= pl.lit(TEST_START)) & (pl.col('updated_date')<=pl.lit(TEST_END)))

In [108]:
display(train_set.head(5).collect(engine = 'streaming'))
display(valid_set.head(5).collect(engine = 'streaming'))
display(test_set.head(5).collect(engine = 'streaming'))

shape: (5, 9)
┌────────────┬────────────┬──────────┬──────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ customer_i ┆ item_id    ┆ price    ┆ location ┆ … ┆ bill_id   ┆ quantity ┆ event_typ ┆ updated_d │
│ d          ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---      ┆ e         ┆ ate       │
│ ---        ┆ str        ┆ f32      ┆ i32      ┆   ┆ i32       ┆ i32      ┆ ---       ┆ ---       │
│ i32        ┆            ┆          ┆          ┆   ┆           ┆          ┆ str       ┆ datetime[ │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ μs]       │
╞════════════╪════════════╪══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 6291331    ┆ 6767000000 ┆ 285000.0 ┆ 1053     ┆ … ┆ 137262467 ┆ 1        ┆ Purchase  ┆ 2025-04-1 │
│            ┆ 002        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2 12:52:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 1.910     │
│ 5505362    ┆ 2265000000 ┆ 195000.0 ┆ 468      ┆ … ┆ 138193104 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 027        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 4 14:57:0 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 0.773     │
│ 7694873    ┆ 6497000000 ┆ 312550.0 ┆ 363      ┆ … ┆ 138230425 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 004        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 4 20:35:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 0.027     │
│ 5837076    ┆ 6587000000 ┆ 149000.0 ┆ 48       ┆ … ┆ 138235471 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 001        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 4 21:12:3 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2.070     │
│ 6781756    ┆ 3880000000 ┆ 79000.0  ┆ 634      ┆ … ┆ 138239415 ┆ 1        ┆ Purchase  ┆ 2025-04-2 │
│            ┆ 002        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 5 08:00:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6.293     │
└────────────┴────────────┴──────────┴──────────┴───┴───────────┴──────────┴───────────┴───────────┘

shape: (5, 9)
┌────────────┬────────────┬──────────┬──────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ customer_i ┆ item_id    ┆ price    ┆ location ┆ … ┆ bill_id   ┆ quantity ┆ event_typ ┆ updated_d │
│ d          ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---      ┆ e         ┆ ate       │
│ ---        ┆ str        ┆ f32      ┆ i32      ┆   ┆ i32       ┆ i32      ┆ ---       ┆ ---       │
│ i32        ┆            ┆          ┆          ┆   ┆           ┆          ┆ str       ┆ datetime[ │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ μs]       │
╞════════════╪════════════╪══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 8316345    ┆ 4268000000 ┆ 301506.0 ┆ 345      ┆ … ┆ 148702063 ┆ 1        ┆ Purchase  ┆ 2025-11-1 │
│            ┆ 069        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 4 14:17:3 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 4.643     │
│ 6705673    ┆ 3522000000 ┆ 119000.0 ┆ 855      ┆ … ┆ 148701832 ┆ 1        ┆ Purchase  ┆ 2025-11-0 │
│            ┆ 083        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 9 12:15:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2.103     │
│ 7942869    ┆ 0009200000 ┆ 49400.0  ┆ 766      ┆ … ┆ 148696856 ┆ 1        ┆ Purchase  ┆ 2025-11-0 │
│            ┆ 049        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2 17:44:1 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 7.273     │
│ 8061416    ┆ 2454000000 ┆ 785000.0 ┆ 174      ┆ … ┆ 148706979 ┆ 1        ┆ Purchase  ┆ 2025-11-2 │
│            ┆ 001        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 3 08:20:5 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 9.147     │
│ 6705673    ┆ 3525000000 ┆ 139000.0 ┆ 855      ┆ … ┆ 148701832 ┆ 1        ┆ Purchase  ┆ 2025-11-0 │
│            ┆ 128        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 9 12:15:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2.103     │
└────────────┴────────────┴──────────┴──────────┴───┴───────────┴──────────┴───────────┴───────────┘

shape: (5, 9)
┌────────────┬────────────┬──────────┬──────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ customer_i ┆ item_id    ┆ price    ┆ location ┆ … ┆ bill_id   ┆ quantity ┆ event_typ ┆ updated_d │
│ d          ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---      ┆ e         ┆ ate       │
│ ---        ┆ str        ┆ f32      ┆ i32      ┆   ┆ i32       ┆ i32      ┆ ---       ┆ ---       │
│ i32        ┆            ┆          ┆          ┆   ┆           ┆          ┆ str       ┆ datetime[ │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ μs]       │
╞════════════╪════════════╪══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 5295052    ┆ 2507000000 ┆ 424080.0 ┆ 761      ┆ … ┆ 148661126 ┆ 11       ┆ Purchase  ┆ 2025-12-1 │
│            ┆ 003        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6 11:27:0 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 2.683     │
│ 7955723    ┆ 0041000000 ┆ 407500.0 ┆ 585      ┆ … ┆ 148653317 ┆ 2        ┆ Purchase  ┆ 2025-12-1 │
│            ┆ 028        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6 11:25:0 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 9.480     │
│ 405233     ┆ 2155000000 ┆ 113240.0 ┆ 717      ┆ … ┆ 148552869 ┆ 1        ┆ Purchase  ┆ 2025-12-1 │
│            ┆ 110        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6 11:22:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 5.320     │
│ 3487571    ┆ 2451000000 ┆ 385000.0 ┆ 342      ┆ … ┆ 148544814 ┆ 1        ┆ Purchase  ┆ 2025-12-1 │
│            ┆ 001        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6 11:59:0 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6.903     │
│ 8269181    ┆ 5856000000 ┆ 480000.0 ┆ 1138     ┆ … ┆ 148296545 ┆ 1        ┆ Purchase  ┆ 2025-12-1 │
│            ┆ 001        ┆          ┆          ┆   ┆           ┆          ┆           ┆ 7 18:50:4 │
│            ┆            ┆          ┆          ┆   ┆           ┆          ┆           ┆ 6.897     │
└────────────┴────────────┴──────────┴──────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [110]:
interaction_lf.sink_parquet('data/full_dataset.parquet')
train_set.sink_parquet('data/train_set.parquet')
valid_set.sink_parquet('data/valid_set.parquet')
test_set.sink_parquet('data/test_set.parquet')